name: aggregate-data
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: https://europe-west1-charlie-tango-dk-stats.cloudfunctions.net/aggregateData
